#if UNITY_EDITOR

using System.Linq;
using EncosyTower.CodeGen;
using EncosyTower.Core;

namespace EncosyTower.Editor.Tasks
{
    [CodeGenerator]
    [ApiForEditor]
    internal sealed class UnityTaskGenerator : ICodeGenerator
    {
        private const int MIN_ARITY = 2;
        private const int MAX_ARITY = 15;

        public GeneratedCode[] Generate()
        {
            var p = Printer.DefaultLarge;
            PrintBackend(
                  ref p
                , guard: "#if !UNITASK"
                , backendUsing: "using UnityEngine;\nusing UnityEngine.Tasks;"
                , backendType: "Awaitables"
                , unwrapMethod: "AsAwaitable"
            );
            var awaitableContent = p.Result;

            p = Printer.DefaultLarge;
            PrintBackend(
                  ref p
                , guard: "#if UNITASK"
                , backendUsing: "using Cysharp.Threading.Tasks;"
                , backendType: "UniTask"
                , unwrapMethod: "AsUniTask"
            );

            return new GeneratedCode[] {
                CodeGenAPI.GetGeneratedCode(awaitableContent, "UnityTask_Awaitable.gen"),
                CodeGenAPI.GetGeneratedCode(p.Result, "UnityTask_UniTask.gen"),
            };
        }

        private static void PrintBackend(
              ref Printer p
            , string guard
            , string backendUsing
            , string backendType
            , string unwrapMethod
        )
        {
            p.PrintAutoGeneratedBlock(nameof(UnityTaskGenerator));
            p.PrintEndLine();
            p.PrintLine(guard);
            p.PrintEndLine();
            p.PrintLine("#pragma warning disable");
            p.PrintEndLine();
            p.PrintLine("using System.Runtime.CompilerServices;");
            p.PrintLine(backendUsing);
            p.PrintEndLine();
            p.PrintLine("namespace EncosyTower.Tasks");
            p.OpenScope();
            {
                p.PrintLine("public readonly partial struct UnityTask");
                p.OpenScope();
                {
                    for (var arity = MIN_ARITY; arity <= MAX_ARITY; arity++)
                    {
                        PrintWhenAll(ref p, arity, backendType, unwrapMethod);
                        PrintWhenAny(ref p, arity, backendType, unwrapMethod);
                    }
                }
                p.CloseScope();
            }
            p.CloseScope();
            p.PrintEndLine();
            p.PrintLine("#endif");
        }

        private static void PrintWhenAll(ref Printer p, int arity, string backendType, string unwrapMethod)
        {
            var typeParameters = GetTypeParameters(arity);

            p.PrintLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            p.PrintLine("public static UnityTask<");
            PrintTupleType(ref p, arity, includeWinner: false);
            p.PrintBeginLine("> WhenAll<").Print(typeParameters).PrintEndLine(">(");
            PrintParameters(ref p, arity);
            p.PrintLine(")");
            p.WithIncreasedIndent().PrintBeginLine("=> new(").Print(backendType).PrintEndLine(".WhenAll(");
            PrintArguments(ref p, arity, unwrapMethod);
            p.WithIncreasedIndent().PrintLine("));");
            p.PrintEndLine();
        }

        private static void PrintWhenAny(ref Printer p, int arity, string backendType, string unwrapMethod)
        {
            var typeParameters = GetTypeParameters(arity);

            p.PrintLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            p.PrintLine("public static UnityTask<");
            PrintTupleType(ref p, arity, includeWinner: true);
            p.PrintBeginLine("> WhenAny<").Print(typeParameters).PrintEndLine(">(");
            PrintParameters(ref p, arity);
            p.PrintLine(")");
            p.WithIncreasedIndent().PrintBeginLine("=> new(").Print(backendType).PrintEndLine(".WhenAny(");
            PrintArguments(ref p, arity, unwrapMethod);
            p.WithIncreasedIndent().PrintLine("));");
            p.PrintEndLine();
        }

        private static void PrintTupleType(ref Printer p, int arity, bool includeWinner)
        {
            p.PrintLine("(");
            p = p.IncreasedIndent();

            if (includeWinner)
            {
                p.PrintLine("  int winArgumentIndex");
            }

            for (var i = 1; i <= arity; i++)
            {
                var prefix = includeWinner || i > 1 ? ", " : "  ";
                var name = includeWinner ? $" result{i}" : "";
                p.PrintLine($"{prefix}T{i}{name}");
            }

            p = p.DecreasedIndent();
            p.PrintLine(")");
        }

        private static void PrintParameters(ref Printer p, int arity)
        {
            p = p.IncreasedIndent();

            for (var i = 1; i <= arity; i++)
            {
                var prefix = i == 1 ? "  " : ", ";
                p.PrintLine($"{prefix}UnityTask<T{i}> task{i}");
            }

            p = p.DecreasedIndent();
        }

        private static void PrintArguments(ref Printer p, int arity, string unwrapMethod)
        {
            p = p.IncreasedIndent();

            for (var i = 1; i <= arity; i++)
            {
                var prefix = i == 1 ? "  " : ", ";
                p.PrintLine($"{prefix}task{i}.{unwrapMethod}()");
            }

            p = p.DecreasedIndent();
        }

        private static string GetTypeParameters(int arity)
            => string.Join(", ", Enumerable.Range(1, arity).Select(static i => $"T{i}"));
    }
}

#endif
