/// <auto-generated>
///***************************************************///
///                                                   ///
/// This file is auto-generated by UnityTaskGenerator ///
///            DO NOT manually modify it!             ///
///                                                   ///
///***************************************************///
/// </auto-generated>

#if !UNITASK

#pragma warning disable

using System.Runtime.CompilerServices;
using UnityEngine;
using UnityEngine.Tasks;

namespace EncosyTower.Tasks
{
    public readonly partial struct UnityTask
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
        )
        > WhenAll<T1, T2>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
        )
        > WhenAny<T1, T2>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
        )
        > WhenAll<T1, T2, T3>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
        )
        > WhenAny<T1, T2, T3>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
        )
        > WhenAll<T1, T2, T3, T4>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
        )
        > WhenAny<T1, T2, T3, T4>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
            , T5
        )
        > WhenAll<T1, T2, T3, T4, T5>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
            , T5 result5
        )
        > WhenAny<T1, T2, T3, T4, T5>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
            , T5
            , T6
        )
        > WhenAll<T1, T2, T3, T4, T5, T6>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
            , T5 result5
            , T6 result6
        )
        > WhenAny<T1, T2, T3, T4, T5, T6>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
            , T5
            , T6
            , T7
        )
        > WhenAll<T1, T2, T3, T4, T5, T6, T7>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
            , T5 result5
            , T6 result6
            , T7 result7
        )
        > WhenAny<T1, T2, T3, T4, T5, T6, T7>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
            , T5
            , T6
            , T7
            , T8
        )
        > WhenAll<T1, T2, T3, T4, T5, T6, T7, T8>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
            , T5 result5
            , T6 result6
            , T7 result7
            , T8 result8
        )
        > WhenAny<T1, T2, T3, T4, T5, T6, T7, T8>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
            , T5
            , T6
            , T7
            , T8
            , T9
        )
        > WhenAll<T1, T2, T3, T4, T5, T6, T7, T8, T9>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
            , T5 result5
            , T6 result6
            , T7 result7
            , T8 result8
            , T9 result9
        )
        > WhenAny<T1, T2, T3, T4, T5, T6, T7, T8, T9>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
            , T5
            , T6
            , T7
            , T8
            , T9
            , T10
        )
        > WhenAll<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
            , T5 result5
            , T6 result6
            , T7 result7
            , T8 result8
            , T9 result9
            , T10 result10
        )
        > WhenAny<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
            , T5
            , T6
            , T7
            , T8
            , T9
            , T10
            , T11
        )
        > WhenAll<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
            , UnityTask<T11> task11
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            , task11.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
            , T5 result5
            , T6 result6
            , T7 result7
            , T8 result8
            , T9 result9
            , T10 result10
            , T11 result11
        )
        > WhenAny<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
            , UnityTask<T11> task11
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            , task11.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
            , T5
            , T6
            , T7
            , T8
            , T9
            , T10
            , T11
            , T12
        )
        > WhenAll<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
            , UnityTask<T11> task11
            , UnityTask<T12> task12
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            , task11.AsAwaitable()
            , task12.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
            , T5 result5
            , T6 result6
            , T7 result7
            , T8 result8
            , T9 result9
            , T10 result10
            , T11 result11
            , T12 result12
        )
        > WhenAny<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
            , UnityTask<T11> task11
            , UnityTask<T12> task12
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            , task11.AsAwaitable()
            , task12.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
            , T5
            , T6
            , T7
            , T8
            , T9
            , T10
            , T11
            , T12
            , T13
        )
        > WhenAll<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
            , UnityTask<T11> task11
            , UnityTask<T12> task12
            , UnityTask<T13> task13
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            , task11.AsAwaitable()
            , task12.AsAwaitable()
            , task13.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
            , T5 result5
            , T6 result6
            , T7 result7
            , T8 result8
            , T9 result9
            , T10 result10
            , T11 result11
            , T12 result12
            , T13 result13
        )
        > WhenAny<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
            , UnityTask<T11> task11
            , UnityTask<T12> task12
            , UnityTask<T13> task13
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            , task11.AsAwaitable()
            , task12.AsAwaitable()
            , task13.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
            , T5
            , T6
            , T7
            , T8
            , T9
            , T10
            , T11
            , T12
            , T13
            , T14
        )
        > WhenAll<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
            , UnityTask<T11> task11
            , UnityTask<T12> task12
            , UnityTask<T13> task13
            , UnityTask<T14> task14
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            , task11.AsAwaitable()
            , task12.AsAwaitable()
            , task13.AsAwaitable()
            , task14.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
            , T5 result5
            , T6 result6
            , T7 result7
            , T8 result8
            , T9 result9
            , T10 result10
            , T11 result11
            , T12 result12
            , T13 result13
            , T14 result14
        )
        > WhenAny<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
            , UnityTask<T11> task11
            , UnityTask<T12> task12
            , UnityTask<T13> task13
            , UnityTask<T14> task14
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            , task11.AsAwaitable()
            , task12.AsAwaitable()
            , task13.AsAwaitable()
            , task14.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              T1
            , T2
            , T3
            , T4
            , T5
            , T6
            , T7
            , T8
            , T9
            , T10
            , T11
            , T12
            , T13
            , T14
            , T15
        )
        > WhenAll<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
            , UnityTask<T11> task11
            , UnityTask<T12> task12
            , UnityTask<T13> task13
            , UnityTask<T14> task14
            , UnityTask<T15> task15
        )
            => new(Awaitables.WhenAll(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            , task11.AsAwaitable()
            , task12.AsAwaitable()
            , task13.AsAwaitable()
            , task14.AsAwaitable()
            , task15.AsAwaitable()
            ));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UnityTask<
        (
              int winArgumentIndex
            , T1 result1
            , T2 result2
            , T3 result3
            , T4 result4
            , T5 result5
            , T6 result6
            , T7 result7
            , T8 result8
            , T9 result9
            , T10 result10
            , T11 result11
            , T12 result12
            , T13 result13
            , T14 result14
            , T15 result15
        )
        > WhenAny<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(
              UnityTask<T1> task1
            , UnityTask<T2> task2
            , UnityTask<T3> task3
            , UnityTask<T4> task4
            , UnityTask<T5> task5
            , UnityTask<T6> task6
            , UnityTask<T7> task7
            , UnityTask<T8> task8
            , UnityTask<T9> task9
            , UnityTask<T10> task10
            , UnityTask<T11> task11
            , UnityTask<T12> task12
            , UnityTask<T13> task13
            , UnityTask<T14> task14
            , UnityTask<T15> task15
        )
            => new(Awaitables.WhenAny(
              task1.AsAwaitable()
            , task2.AsAwaitable()
            , task3.AsAwaitable()
            , task4.AsAwaitable()
            , task5.AsAwaitable()
            , task6.AsAwaitable()
            , task7.AsAwaitable()
            , task8.AsAwaitable()
            , task9.AsAwaitable()
            , task10.AsAwaitable()
            , task11.AsAwaitable()
            , task12.AsAwaitable()
            , task13.AsAwaitable()
            , task14.AsAwaitable()
            , task15.AsAwaitable()
            ));

    }
}

#endif
