namespace EncosyTower.Core.Analyzers.Variants
{
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    internal sealed class VariantAnalyzer : DiagnosticAnalyzer
    {
        private const string NAMESPACE_PREFIX = "global::EncosyTower.Variants";
        private const string VARIANT_ATTRIBUTE = $"{NAMESPACE_PREFIX}.VariantAttribute";
        private const string VARIANT_T = $"{NAMESPACE_PREFIX}.Variant<";
        private const string CONVERTER_T = $"{NAMESPACE_PREFIX}.Converters.CachedVariantConverter<";
        private const string VARIANT_NAME = "Variant";
        private const string GET_CONVERTER_NAME = "GetConverter";
        private const string CACHED_CONVERTER_NAME = "CachedVariantConverter";
        private const string DEFAULT_NAME = "Default";
        private const string VARIANT_DISPLAY = "[Variant]";
        private const string GET_CONVERTER_DISPLAY = "Variant<T>.GetConverter";
        private const string CACHED_CONVERTER_DISPLAY = "CachedVariantConverter<T>.Default";

        public static readonly DiagnosticDescriptor VariantTypeIsGenerated = new(
              id: "SG_VARIANT_0001"
            , title: "Variant type is generated by another source generator"
            , messageFormat: "\"{0}\" is generated by {3}, so the generator for {1} on \"{2}\" cannot see it. " +
                "Declare \"{0}\" in hand-written source or move it to a referenced assembly."
            , category: "Variants"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "Variant type is generated by another source generator."
        );

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
            => ImmutableArray.Create(VariantTypeIsGenerated);

        public override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
            context.EnableConcurrentExecution();
            context.RegisterSymbolAction(AnalyzeVariantStruct, SymbolKind.NamedType);
            context.RegisterSyntaxNodeAction(AnalyzeConverterAccess, SyntaxKind.SimpleMemberAccessExpression);
        }

        private static void AnalyzeVariantStruct(SymbolAnalysisContext context)
        {
            var token = context.CancellationToken;
            token.ThrowIfCancellationRequested();

            if (context.Symbol is not INamedTypeSymbol { TypeKind: TypeKind.Struct } structSymbol
                || structSymbol.TryGetAttribute(VARIANT_ATTRIBUTE, out var attribute, token) == false
                || attribute.ConstructorArguments.Length < 1
                || attribute.ConstructorArguments[0].Value is not ITypeSymbol variantType
                || variantType.TryFindEncosyTowerGeneratedType(token, out var generatedType, out var tool) == false
            )
            {
                return;
            }

            var location = attribute.TryGetTypeOfOperandLocation(token, out var typeOfLocation)
                ? typeOfLocation
                : structSymbol.Locations[0];

            context.ReportDiagnostic(Diagnostic.Create(
                  VariantTypeIsGenerated
                , location
                , generatedType.ToGeneratedTypeFullName()
                , VARIANT_DISPLAY
                , structSymbol.Name
                , tool
            ));
        }

        private static void AnalyzeConverterAccess(SyntaxNodeAnalysisContext context)
        {
            var token = context.CancellationToken;
            token.ThrowIfCancellationRequested();

            if (context.Node is not MemberAccessExpressionSyntax syntax
                || syntax.Expression is not GenericNameSyntax typeSyntax
                || syntax.Name is not IdentifierNameSyntax memberSyntax
                || typeSyntax.TypeArgumentList.Arguments.Count != 1
            )
            {
                return;
            }

            var typeName = typeSyntax.Identifier.ValueText;

            if (IsConverterAccess(typeName, memberSyntax.Identifier.ValueText) == false)
            {
                return;
            }

            var typeInfo = context.SemanticModel.GetTypeInfo(typeSyntax, token).Type;

            if (typeInfo is not INamedTypeSymbol type
                || type.TypeArguments.Length != 1
                || type.TypeArguments[0] is not INamedTypeSymbol typeArg
                || typeArg.IsUnboundGenericType
                || (typeArg.IsGenericType && typeArg.TypeParameters.Length != 0)
            )
            {
                return;
            }

            if (type.HasFullNamePrefix(VARIANT_T, token) == false
                && type.HasFullNamePrefix(CONVERTER_T, token) == false
            )
            {
                return;
            }

            if (typeArg.TryFindEncosyTowerGeneratedType(token, out var generatedType, out var tool) == false)
            {
                return;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                  VariantTypeIsGenerated
                , typeSyntax.TypeArgumentList.Arguments[0].GetLocation()
                , generatedType.ToGeneratedTypeFullName()
                , typeName is VARIANT_NAME ? GET_CONVERTER_DISPLAY : CACHED_CONVERTER_DISPLAY
                , typeArg.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)
                , tool
            ));
        }

        private static bool IsConverterAccess(string typeName, string memberName)
            => (typeName is VARIANT_NAME && memberName is GET_CONVERTER_NAME)
            || (typeName is CACHED_CONVERTER_NAME && memberName is DEFAULT_NAME);
    }
}
