/// <auto-generated>
///***********************************************************///
///                                                           ///
/// This file is auto-generated by AnyToUIntAdaptersGenerator ///
///                DO NOT manually modify it!                 ///
///                                                           ///
///***********************************************************///
/// </auto-generated>

#pragma warning disable

using System;
using EncosyTower.Annotations;
using EncosyTower.Variants;
using UnityEngine.Scripting.APIUpdating;

namespace EncosyTower.Mvvm.ViewBinding.Adapters
{
    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Byte ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(byte), destType: typeof(uint), order: 0)]
    public sealed class ByteToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out byte result))
            {
                return (uint)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("SByte ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(sbyte), destType: typeof(uint), order: 0)]
    public sealed class SByteToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out sbyte result))
            {
                return (uint)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Char ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(char), destType: typeof(uint), order: 0)]
    public sealed class CharToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out char result))
            {
                return (uint)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Double ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(double), destType: typeof(uint), order: 0)]
    public sealed class DoubleToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out double result))
            {
                return (uint)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Float ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(float), destType: typeof(uint), order: 0)]
    public sealed class FloatToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out float result))
            {
                return (uint)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Int ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(int), destType: typeof(uint), order: 0)]
    public sealed class IntToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out int result))
            {
                return (uint)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("UInt ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(uint), destType: typeof(uint), order: 0)]
    public sealed class UIntToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out uint result))
            {
                return (uint)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Long ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(long), destType: typeof(uint), order: 0)]
    public sealed class LongToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out long result))
            {
                return (uint)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("ULong ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(ulong), destType: typeof(uint), order: 0)]
    public sealed class ULongToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out ulong result))
            {
                return (uint)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Short ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(short), destType: typeof(uint), order: 0)]
    public sealed class ShortToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out short result))
            {
                return (uint)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("UShort ⇒ UInt", "Default")]
    [Adapter(sourceType: typeof(ushort), destType: typeof(uint), order: 0)]
    public sealed class UShortToUIntAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out ushort result))
            {
                return (uint)result;
            }

            return variant;
        }
    }

}

