/// <auto-generated>
///************************************************************///
///                                                            ///
/// This file is auto-generated by AnyToULongAdaptersGenerator ///
///                 DO NOT manually modify it!                 ///
///                                                            ///
///************************************************************///
/// </auto-generated>

#pragma warning disable

using System;
using EncosyTower.Annotations;
using EncosyTower.Variants;
using UnityEngine.Scripting.APIUpdating;

namespace EncosyTower.Mvvm.ViewBinding.Adapters
{
    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Byte ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(byte), destType: typeof(ulong), order: 0)]
    public sealed class ByteToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out byte result))
            {
                return (ulong)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("SByte ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(sbyte), destType: typeof(ulong), order: 0)]
    public sealed class SByteToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out sbyte result))
            {
                return (ulong)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Char ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(char), destType: typeof(ulong), order: 0)]
    public sealed class CharToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out char result))
            {
                return (ulong)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Double ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(double), destType: typeof(ulong), order: 0)]
    public sealed class DoubleToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out double result))
            {
                return (ulong)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Float ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(float), destType: typeof(ulong), order: 0)]
    public sealed class FloatToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out float result))
            {
                return (ulong)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Int ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(int), destType: typeof(ulong), order: 0)]
    public sealed class IntToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out int result))
            {
                return (ulong)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("UInt ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(uint), destType: typeof(ulong), order: 0)]
    public sealed class UIntToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out uint result))
            {
                return (ulong)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Long ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(long), destType: typeof(ulong), order: 0)]
    public sealed class LongToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out long result))
            {
                return (ulong)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("ULong ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(ulong), destType: typeof(ulong), order: 0)]
    public sealed class ULongToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out ulong result))
            {
                return (ulong)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("Short ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(short), destType: typeof(ulong), order: 0)]
    public sealed class ShortToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out short result))
            {
                return (ulong)result;
            }

            return variant;
        }
    }

    [Serializable]
    [MovedFrom(true, sourceNamespace: null, sourceAssembly: "EncosyTower.Core", sourceClassName: null)]
    [Label("UShort ⇒ ULong", "Default")]
    [Adapter(sourceType: typeof(ushort), destType: typeof(ulong), order: 0)]
    public sealed class UShortToULongAdapter : IAdapter
    {
        public Variant Convert(in Variant variant)
        {
            if (variant.TryGetValue(out ushort result))
            {
                return (ulong)result;
            }

            return variant;
        }
    }

}

