#if UNITY_EDITOR

using System;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Runtime.CompilerServices;
using EncosyTower.Common;
using EncosyTower.Core;
using UnityEngine;

using DebuggingThrowHelper = EncosyTower.Debugging.ThrowHelper;

namespace EncosyTower.CodeGen
{
    [ApiForEditor]
    public static class CodeGenAPI
    {
        [ApiForEditor]
        public static GeneratedCode GetGeneratedCode(
              [NotNull] string content
            , [NotNull] string fileName
            , string pathCombine = ""
            , [NotNull] string extension = "cs"
            , [CallerFilePath] string filePath = ""
        )
        {
            DebuggingThrowHelper.ThrowIfNullOrEmpty(content);
            DebuggingThrowHelper.ThrowIfNullOrEmpty(fileName);
            DebuggingThrowHelper.ThrowIfNullOrEmpty(extension);

            var directoryPath = Path.GetDirectoryName(filePath);
            directoryPath = pathCombine.IsNotEmpty() ? Path.Combine(directoryPath, pathCombine) : directoryPath;

            var filePathResult = Path.Combine(directoryPath, $"{fileName}.{extension}");
            return new GeneratedCode(content, filePathResult);
        }

        [ApiForEditor]
        public static Printer PrintAutoGeneratedBlock(
              ref this Printer p
            , string generatorName
            , string resourcePath = ""
        )
        {
            if (string.IsNullOrWhiteSpace(generatorName))
            {
                generatorName = "Unnamed Code Generator";
            }

            var generatorNameLength = generatorName.Length;
            var resourcePathLength = 0;

            if (string.IsNullOrWhiteSpace(resourcePath) == false)
            {
                resourcePathLength = resourcePath.Length;
            }

            var generatorLineLength = 31 + generatorNameLength;
            var starCount = Mathf.Max(resourcePathLength, generatorLineLength);

            p.PrintLine("/// <auto-generated>");
            p.PrintBeginLine("///*");
            p.Print('*', starCount);
            p.PrintEndLine("*///");

            p.PrintBeginLine("/// ");
            p.Print(' ', starCount);
            p.PrintEndLine(" ///");

            {
                var spaceCount = Mathf.Max(starCount - generatorLineLength, 0);
                var firstPartCount = (int)Math.Floor(spaceCount / 2f);
                var lastPartCount = (int)Math.Ceiling(spaceCount / 2f);

                p.PrintBeginLine("/// ");
                p.Print(' ', firstPartCount);
                p.Print("This file is auto-generated by ");
                p.Print(generatorName);
                p.Print(' ', lastPartCount);
                p.PrintEndLine(" ///");
            }

            if (resourcePathLength > 0)
            {
                var spaceCount = Mathf.Max(starCount - resourcePathLength, 0);
                var firstPartCount = (int)Math.Floor(spaceCount / 2f);
                var lastPartCount = (int)Math.Ceiling(spaceCount / 2f);

                p.PrintBeginLine("/// ");
                p.Print(' ', firstPartCount);
                p.Print(resourcePath);
                p.Print(' ', lastPartCount);
                p.PrintEndLine(" ///");
            }

            {
                var spaceCount = Mathf.Max(starCount - 26, 0);
                var firstPartCount = (int)Math.Floor(spaceCount / 2f);
                var lastPartCount = (int)Math.Ceiling(spaceCount / 2f);

                p.PrintBeginLine("/// ");
                p.Print(' ', firstPartCount);
                p.Print("DO NOT manually modify it!");
                p.Print(' ', lastPartCount);
                p.PrintEndLine(" ///");
            }

            p.PrintBeginLine("/// ");
            p.Print(' ', starCount);
            p.PrintEndLine(" ///");

            p.PrintBeginLine("///*");
            p.Print('*', starCount);
            p.PrintEndLine("*///");
            p.PrintLine("/// </auto-generated>");

            return p;
        }

        [ApiForEditor]
        public static string GetBuiltInNameOrDefault(this Type type)
        {
            if (type == null) return string.Empty;

            return type.FullName switch {
                "System.Boolean" => "bool",
                "System.Byte" => "byte",
                "System.SByte" => "sbyte",
                "System.Char" => "char",
                "System.Decimal" => "decimal",
                "System.Double" => "double",
                "System.Single" => "float",
                "System.Int32" => "int",
                "System.UInt32" => "uint",
                "System.IntPtr" => "nint",
                "System.UIntPtr" => "nuint",
                "System.Int64" => "long",
                "System.UInt64" => "ulong",
                "System.Int16" => "short",
                "System.UInt16" => "ushort",
                "System.Object" => "object",
                "System.String" => "string",
                _ => type.FullName,
            };
        }
    }
}

#endif
