#if UNITY_EDITOR

using System;
using EncosyTower.CodeGen;
using EncosyTower.Common;
using EncosyTower.Core;

namespace EncosyTower.Editor.Mvvm.ViewBinding.Adapters.Unity
{
    [CodeGenerator]
    [ApiForEditor]
    internal class AnyResoucesAdaptersGenerator : ICodeGenerator
    {
        public GeneratedCode[] Generate()
        {
            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(nameof(AnyResoucesAdaptersGenerator));
            p.PrintEndLine();
            p.PrintLine(@"#pragma warning disable

using System;
using EncosyTower.Annotations;
using EncosyTower.Variants.Converters;
");

            p.PrintEndLine();
            p.PrintLine("namespace EncosyTower.Mvvm.ViewBinding.Adapters.Unity");
            p.OpenScope();
            {
                var unityTypes = MvvmCodeGenAPI.UnityTypes.AsSpan();

                for (var i = 0; i < unityTypes.Length; i++)
                {
                    var group = unityTypes[i];
                    var condition = group.Condition ?? string.Empty;
                    var types = group.Types.AsSpan();

                    if (condition.IsNotEmpty())
                    {
                        p.Print("#if ").PrintEndLine(condition);
                    }

                    for (var k = 0; k < types.Length; k++)
                    {
                        var type = types[k];
                        var name = type.Name;
                        var typeName = type.FullName;

                        p.PrintLine($"[Serializable]");
                        p.PrintLine($"[Label(\"Resources.Load<{typeName}>(string)\", \"Default\")]");
                        p.PrintLine($"[Adapter(sourceType: typeof(string), destType: typeof({typeName}), order: 0)]");
                        p.PrintLine($"public sealed class {name}ResourcesAdapter : ResourcesAdapter<{typeName}>");
                        p.OpenScope();
                        {
                            p.PrintBeginLine($"public ")
                                .Print(name)
                                .Print("ResourcesAdapter() : base(CachedVariantConverter<")
                                .Print(typeName)
                                .PrintEndLine(">.Default) { }");
                        }
                        p.CloseScope();
                        p.PrintEndLine();
                    }

                    if (condition.IsNotEmpty())
                    {
                        p.Print("#endif").PrintEndLine().PrintEndLine();
                    }
                }
            }
            p.CloseScope();
            p.PrintEndLine();

            return new GeneratedCode[] {
                CodeGenAPI.GetGeneratedCode(p.Result, "AnyResoucesAdapters.gen"),
            };
        }
    }
}

#endif
