namespace EncosyTower.Data.Analyzers.DataTableAssets
{
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    internal sealed class DataTableAssetAnalyzer : DiagnosticAnalyzer
    {
        private const string DATA_TABLE_ASSET = "global::EncosyTower.Databases.DataTableAsset";
        private const string DATA_TABLE_ASSET_ATTRIBUTE = "EncosyTower.Databases.DataTableAssetAttribute";
        private const string DATA_TABLE_ASSET_DISPLAY = "[DataTableAsset]";
        private const string GET_ID = "GetId";
        private const string CONVERT_ID = "ConvertId";

        public static readonly DiagnosticDescriptor MustBeApplicableForTypeArgument = new(
              id: "SG_DATA_TABLE_ASSET_0001"
            , title: "Must be either a struct, a class or an enum to replace type argument"
            , messageFormat: "Type \"{0}\" is not applicable to replace \"{1}\", must be either a struct, a class or an enum"
            , category: "DataTableAssetGenerator"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "Must be either a struct, a class or an enum."
        );

        public static readonly DiagnosticDescriptor TypeArgumentIsGenerated = new(
              id: "SG_DATA_TABLE_ASSET_0002"
            , title: "DataTableAsset type argument is generated by another source generator"
            , messageFormat: "\"{0}\" is generated by {3}, so the generator for {1} on \"{2}\" cannot see it. "
                + "Declare \"{0}\" in hand-written source or move it to a referenced assembly."
            , category: "DataTableAssetGenerator"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "DataTableAsset type argument is generated by another source generator."
        );

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
            => ImmutableArray.Create(
                  MustBeApplicableForTypeArgument
                , TypeArgumentIsGenerated
            );

        public override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
            context.EnableConcurrentExecution();
            context.RegisterSymbolAction(AnalyzeNamedType, SymbolKind.NamedType);
        }

        private static void AnalyzeNamedType(SymbolAnalysisContext context)
        {
            var token = context.CancellationToken;
            token.ThrowIfCancellationRequested();

            if (context.Symbol is not INamedTypeSymbol typeSymbol)
            {
                return;
            }

            var hasAttribute = false;

            foreach (var attr in typeSymbol.GetAttributes())
            {
                token.ThrowIfCancellationRequested();

                var attrClass = attr.AttributeClass;

                if (attrClass is null)
                {
                    continue;
                }

                if (attrClass.HasFullName(DATA_TABLE_ASSET_ATTRIBUTE, token))
                {
                    hasAttribute = true;
                    break;
                }
            }

            token.ThrowIfCancellationRequested();

            if (hasAttribute == false)
            {
                return;
            }

            var baseType = typeSymbol.BaseType;

            while (baseType != null)
            {
                token.ThrowIfCancellationRequested();

                var typeArguments = baseType.TypeArguments;

                if (typeArguments.Length >= 2)
                {
                    if (baseType.HasFullNamePrefix(DATA_TABLE_ASSET, token))
                    {
                        var idType = typeArguments[0];
                        var dataType = typeArguments[1];
                        if (typeSymbol.TryGetSourceLocation(out var typeLocation) == false)
                        {
                            return;
                        }

                        if (idType.TypeKind is not (TypeKind.Struct or TypeKind.Class or TypeKind.Enum))
                        {
                            context.ReportDiagnostic(Diagnostic.Create(
                                  MustBeApplicableForTypeArgument
                                , typeLocation
                                , idType.Name
                                , "TDataId"
                            ));
                        }

                        if (dataType.TypeKind is not (TypeKind.Struct or TypeKind.Class or TypeKind.Enum))
                        {
                            context.ReportDiagnostic(Diagnostic.Create(
                                  MustBeApplicableForTypeArgument
                                , typeLocation
                                , dataType.Name
                                , "TData"
                            ));
                        }

                        ReportGeneratedTypeArguments(context, typeSymbol, baseType, typeLocation);
                        return;
                    }
                }

                baseType = baseType.BaseType;
            }
        }

        private static void ReportGeneratedTypeArguments(
              SymbolAnalysisContext context
            , INamedTypeSymbol typeSymbol
            , INamedTypeSymbol assetBaseType
            , Location typeLocation
        )
        {
            var token = context.CancellationToken;
            var typeArguments = assetBaseType.TypeArguments;

            if (typeSymbol.IsAbstract
                || typeSymbol.IsGenericType
                || HasHandWrittenMethod(typeSymbol, GET_ID, RefKind.In, typeArguments[1], token)
            )
            {
                return;
            }

            ReportGeneratedTypeArgument(context, typeSymbol, assetBaseType, 0, typeLocation);
            ReportGeneratedTypeArgument(context, typeSymbol, assetBaseType, 1, typeLocation);

            if (typeArguments.Length > 2
                && HasHandWrittenMethod(typeSymbol, CONVERT_ID, RefKind.None, typeArguments[0], token) == false
            )
            {
                ReportGeneratedTypeArgument(context, typeSymbol, assetBaseType, 2, typeLocation);
            }
        }

        private static void ReportGeneratedTypeArgument(
              SymbolAnalysisContext context
            , INamedTypeSymbol typeSymbol
            , INamedTypeSymbol assetBaseType
            , int index
            , Location typeLocation
        )
        {
            var token = context.CancellationToken;

            if (assetBaseType.TypeArguments[index].TryFindEncosyTowerGeneratedType(
                  token
                , out var generatedType
                , out var tool
            ) == false)
            {
                return;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                  TypeArgumentIsGenerated
                , GetTypeArgumentLocation(typeSymbol, assetBaseType, index, token) ?? typeLocation
                , generatedType.ToGeneratedTypeFullName()
                , DATA_TABLE_ASSET_DISPLAY
                , typeSymbol.Name
                , tool
            ));
        }

        private static bool HasHandWrittenMethod(
              INamedTypeSymbol typeSymbol
            , string name
            , RefKind refKind
            , ITypeSymbol parameterType
            , CancellationToken token
        )
        {
            foreach (var member in typeSymbol.GetMembers(name))
            {
                token.ThrowIfCancellationRequested();

                if (member is IMethodSymbol { Parameters: { Length: 1 } parameters } method
                    && parameters[0].RefKind == refKind
                    && SymbolEqualityComparer.Default.Equals(parameters[0].Type, parameterType)
                    && method.DeclaringSyntaxReferences.Length > 0
                    && method.HasOnlyGeneratedDeclarations(token) == false
                )
                {
                    return true;
                }
            }

            return false;
        }

        private static Location GetTypeArgumentLocation(
              INamedTypeSymbol typeSymbol
            , INamedTypeSymbol assetBaseType
            , int index
            , CancellationToken token
        )
        {
            var isDirectBase = SymbolEqualityComparer.Default.Equals(typeSymbol.BaseType, assetBaseType);

            foreach (var reference in typeSymbol.DeclaringSyntaxReferences)
            {
                token.ThrowIfCancellationRequested();

                if (reference.GetSyntax(token)
                    is not ClassDeclarationSyntax { BaseList.Types: { Count: > 0 } baseTypes }
                )
                {
                    continue;
                }

                var baseTypeSyntax = baseTypes[0].Type;

                if (isDirectBase
                    && GetGenericName(baseTypeSyntax) is { } genericName
                    && genericName.TypeArgumentList.Arguments.Count == assetBaseType.TypeArguments.Length
                )
                {
                    return genericName.TypeArgumentList.Arguments[index].GetLocation();
                }

                return baseTypeSyntax.GetLocation();
            }

            return null;
        }

        private static GenericNameSyntax GetGenericName(TypeSyntax syntax)
            => syntax switch {
                GenericNameSyntax genericName => genericName,
                QualifiedNameSyntax { Right: GenericNameSyntax genericName } => genericName,
                AliasQualifiedNameSyntax { Name: GenericNameSyntax genericName } => genericName,
                _ => null,
            };
    }
}
