namespace EncosyTower.Core.Analyzers.TypeWraps
{
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    internal sealed class TypeWrapDiagnosticAnalyzer : DiagnosticAnalyzer
    {
        private const string NAMESPACE = "EncosyTower.TypeWraps";
        private const string WRAP_TYPE_FQN = $"global::{NAMESPACE}.WrapTypeAttribute";
        private const string WRAP_RECORD_FQN = $"global::{NAMESPACE}.WrapRecordAttribute";
        private const string CATEGORY = "TypeWrapGenerator";
        private const string WRAP_TYPE = "WrapType";
        private const string WRAP_RECORD = "WrapRecord";
        private const string WRAP_TYPE_DISPLAY = $"[{WRAP_TYPE}]";
        private const string WRAP_RECORD_DISPLAY = $"[{WRAP_RECORD}]";

        public static readonly DiagnosticDescriptor WrapTypeOnRecord = new(
              id: "SG_TYPE_WRAP_0001"
            , title: "[WrapType] is not allowed on record"
            , messageFormat: "[WrapType] cannot be applied to record type \"{0}\". Use [WrapRecord] instead."
            , category: CATEGORY
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "[WrapType] is not allowed on record."
        );

        public static readonly DiagnosticDescriptor NotTypeOfExpression = new(
              id: "SG_TYPE_WRAP_0002"
            , title: "[WrapType] first argument must be a typeof expression"
            , messageFormat: "[WrapType] on \"{0}\" requires the first argument to be a typeof(...) expression"
            , category: CATEGORY
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "[WrapType] first argument must be a typeof expression."
        );

        public static readonly DiagnosticDescriptor InvalidMemberName = new(
              id: "SG_TYPE_WRAP_0003"
            , title: "[WrapType] MemberName must be a valid C# identifier"
            , messageFormat: "[WrapType] on \"{0}\" requires MemberName \"{1}\" to be a non-empty, valid C# identifier"
            , category: CATEGORY
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "[WrapType] MemberName must be a valid C# identifier."
        );

        public static readonly DiagnosticDescriptor WrapRecordRequiresOneParameter = new(
              id: "SG_TYPE_WRAP_0004"
            , title: "[WrapRecord] requires a positional record with exactly one parameter"
            , messageFormat: "[WrapRecord] on \"{0}\" requires a positional record declaration with exactly one parameter"
            , category: CATEGORY
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "[WrapRecord] requires a positional record with exactly one parameter."
        );

        public static readonly DiagnosticDescriptor WrapperInheritsBaseClass = new(
              id: "SG_TYPE_WRAP_0005"
            , title: "Wrapper class must not inherit a base class"
            , messageFormat: "Wrapper class \"{0}\" must not inherit a base class other than System.Object"
            , category: CATEGORY
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "Wrapper class must not inherit a base class."
        );

        public static readonly DiagnosticDescriptor WrapRecordOnNonRecord = new(
              id: "SG_TYPE_WRAP_0006"
            , title: "[WrapRecord] is not allowed on non-record declaration"
            , messageFormat: "[WrapRecord] cannot be applied to \"{0}\" because it is not a record declaration"
            , category: CATEGORY
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "[WrapRecord] is not allowed on non-record declaration."
        );

        public static readonly DiagnosticDescriptor WrappedTypeMustBeNamedType = new(
              id: "SG_TYPE_WRAP_0007"
            , title: "Wrapped type must be a named type"
            , messageFormat: "[{0}] on \"{1}\" cannot wrap \"{2}\" because it is not a named type"
            , category: CATEGORY
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "The type wrapped by [WrapType] or [WrapRecord] must be a named type, not an array, "
                + "type parameter, pointer, function pointer or dynamic type."
        );

        public static readonly DiagnosticDescriptor WrappedTypeIsGenerated = new(
              id: "SG_TYPE_WRAP_0008"
            , title: "TypeWrap wrapped type is generated by another source generator"
            , messageFormat: "\"{0}\" is generated by {3}, so the generator for {1} on \"{2}\" cannot see it. "
                + "Declare \"{0}\" in hand-written source or move it to a referenced assembly."
            , category: CATEGORY
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "TypeWrap wrapped type is generated by another source generator."
        );

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
            => ImmutableArray.Create(
                  WrapTypeOnRecord
                , NotTypeOfExpression
                , InvalidMemberName
                , WrapRecordRequiresOneParameter
                , WrapperInheritsBaseClass
                , WrapRecordOnNonRecord
                , WrappedTypeMustBeNamedType
                , WrappedTypeIsGenerated
            );

        public override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
            context.EnableConcurrentExecution();
            context.RegisterSymbolAction(AnalyzeSymbol, SymbolKind.NamedType);
        }

        private static void AnalyzeSymbol(SymbolAnalysisContext context)
        {
            var token = context.CancellationToken;
            token.ThrowIfCancellationRequested();

            if (context.Symbol is not INamedTypeSymbol typeSymbol)
            {
                return;
            }

            var hasWrapType = typeSymbol.TryGetAttribute(WRAP_TYPE_FQN, out var wrapTypeAttr, token);
            var hasWrapRecord = typeSymbol.TryGetAttribute(WRAP_RECORD_FQN, out var wrapRecordAttr, token);

            if (hasWrapType == false && hasWrapRecord == false)
            {
                return;
            }

            if (hasWrapType)
            {
                AnalyzeWrapType(context, typeSymbol, wrapTypeAttr);
            }

            if (hasWrapRecord)
            {
                AnalyzeWrapRecord(context, typeSymbol, wrapRecordAttr);
            }

            if (typeSymbol.TypeKind == TypeKind.Class && InheritsNonObjectBaseClass(typeSymbol, token))
            {
                var attr = wrapTypeAttr ?? wrapRecordAttr;

                if (attr.TryGetSourceLocation(token, out var location))
                {
                    context.ReportDiagnostic(Diagnostic.Create(WrapperInheritsBaseClass, location, typeSymbol.Name));
                }
            }
        }

        private static void AnalyzeWrapType(
              SymbolAnalysisContext context
            , INamedTypeSymbol typeSymbol
            , AttributeData attr
        )
        {
            if (attr.TryGetSourceLocation(context.CancellationToken, out var location) == false)
            {
                return;
            }

            if (typeSymbol.IsRecord)
            {
                context.ReportDiagnostic(Diagnostic.Create(WrapTypeOnRecord, location, typeSymbol.Name));
                return;
            }

            var args = attr.ConstructorArguments;

            if (args.Length < 1
                || args[0].Kind != TypedConstantKind.Type
                || args[0].Value is not ITypeSymbol wrappedType
            )
            {
                context.ReportDiagnostic(Diagnostic.Create(NotTypeOfExpression, location, typeSymbol.Name));
                return;
            }

            if (wrappedType is not INamedTypeSymbol namedWrappedType)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                      WrappedTypeMustBeNamedType
                    , GetTypeOfOperandLocation(attr, context.CancellationToken) ?? location
                    , WRAP_TYPE
                    , typeSymbol.Name
                    , wrappedType.ToFullName()
                ));
            }
            else
            {
                ReportGeneratedWrappedType(
                      context
                    , typeSymbol
                    , namedWrappedType
                    , GetTypeOfOperandLocation(attr, context.CancellationToken) ?? location
                    , WRAP_TYPE_DISPLAY
                );
            }

            if (args.Length >= 2 && args[1].Kind == TypedConstantKind.Primitive)
            {
                var memberName = args[1].Value as string;

                if (IsValidMemberName(memberName) == false)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                          InvalidMemberName
                        , location
                        , typeSymbol.Name
                        , memberName ?? string.Empty
                    ));
                }
            }
        }

        private static bool IsValidMemberName(string name)
        {
            if (SyntaxFacts.IsValidIdentifier(name) == false)
            {
                return false;
            }

            if (SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None)
            {
                return false;
            }

            return true;
        }

        private static void AnalyzeWrapRecord(
              SymbolAnalysisContext context
            , INamedTypeSymbol typeSymbol
            , AttributeData attr
        )
        {
            var token = context.CancellationToken;

            if (attr.TryGetSourceLocation(token, out var location) == false)
            {
                return;
            }

            if (typeSymbol.IsRecord == false)
            {
                context.ReportDiagnostic(Diagnostic.Create(WrapRecordOnNonRecord, location, typeSymbol.Name));
                return;
            }

            if (TryGetRecordParameterList(typeSymbol, out var parameterList, token) == false
                || parameterList.Parameters.Count != 1
            )
            {
                context.ReportDiagnostic(Diagnostic.Create(WrapRecordRequiresOneParameter, location, typeSymbol.Name));
                return;
            }

            var parameterSyntax = parameterList.Parameters[0];

            if (parameterSyntax.Type == null
                || TryGetPositionalParameterType(typeSymbol, parameterSyntax, out var wrappedType, token) == false
            )
            {
                return;
            }

            if (wrappedType is INamedTypeSymbol namedWrappedType)
            {
                ReportGeneratedWrappedType(
                      context
                    , typeSymbol
                    , namedWrappedType
                    , parameterSyntax.Type.GetLocation()
                    , WRAP_RECORD_DISPLAY
                );

                return;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                  WrappedTypeMustBeNamedType
                , parameterSyntax.Type.GetLocation()
                , WRAP_RECORD
                , typeSymbol.Name
                , wrappedType.ToFullName()
            ));
        }

        private static void ReportGeneratedWrappedType(
              SymbolAnalysisContext context
            , INamedTypeSymbol typeSymbol
            , INamedTypeSymbol wrappedType
            , Location location
            , string attributeName
        )
        {
            if (wrappedType.TryFindEncosyTowerGeneratedType(
                  context.CancellationToken
                , out var generatedType
                , out var tool
            ) == false
            )
            {
                return;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                  WrappedTypeIsGenerated
                , location
                , generatedType.ToGeneratedTypeFullName()
                , attributeName
                , typeSymbol.Name
                , tool
            ));
        }

        private static bool TryGetRecordParameterList(
              INamedTypeSymbol typeSymbol
            , out ParameterListSyntax parameterList
            , CancellationToken token
        )
        {
            token.ThrowIfCancellationRequested();

            var references = typeSymbol.DeclaringSyntaxReferences;
            var count = references.Length;

            for (var i = 0; i < count; i++)
            {
                token.ThrowIfCancellationRequested();

                if (references[i].GetSyntax(token) is RecordDeclarationSyntax recordSyntax
                    && recordSyntax.ParameterList != null
                )
                {
                    parameterList = recordSyntax.ParameterList;
                    return true;
                }
            }

            parameterList = null;
            return false;
        }

        private static bool TryGetPositionalParameterType(
              INamedTypeSymbol typeSymbol
            , ParameterSyntax parameterSyntax
            , out ITypeSymbol parameterType
            , CancellationToken token
        )
        {
            var constructors = typeSymbol.InstanceConstructors;
            var constructorCount = constructors.Length;

            for (var i = 0; i < constructorCount; i++)
            {
                token.ThrowIfCancellationRequested();

                var parameters = constructors[i].Parameters;

                if (parameters.Length != 1)
                {
                    continue;
                }

                var references = parameters[0].DeclaringSyntaxReferences;
                var referenceCount = references.Length;

                for (var k = 0; k < referenceCount; k++)
                {
                    var reference = references[k];

                    if (reference.SyntaxTree == parameterSyntax.SyntaxTree && reference.Span == parameterSyntax.Span)
                    {
                        parameterType = parameters[0].Type;
                        return true;
                    }
                }
            }

            parameterType = null;
            return false;
        }

        private static Location GetTypeOfOperandLocation(AttributeData attribute, CancellationToken token)
        {
            token.ThrowIfCancellationRequested();

            if (attribute.ApplicationSyntaxReference?.GetSyntax(token) is not AttributeSyntax syntax
                || syntax.ArgumentList == null
            )
            {
                return null;
            }

            var arguments = syntax.ArgumentList.Arguments;
            var count = arguments.Count;

            for (var i = 0; i < count; i++)
            {
                var argument = arguments[i];

                if (argument.NameEquals == null && argument.Expression is TypeOfExpressionSyntax typeOf)
                {
                    return typeOf.Type.GetLocation();
                }
            }

            return null;
        }

        private static bool InheritsNonObjectBaseClass(INamedTypeSymbol typeSymbol, CancellationToken token)
        {
            token.ThrowIfCancellationRequested();

            var baseType = typeSymbol.BaseType;

            while (baseType != null)
            {
                token.ThrowIfCancellationRequested();

                if (baseType.TypeKind == TypeKind.Class
                    && baseType.SpecialType != SpecialType.System_Object
                )
                {
                    return true;
                }

                baseType = baseType.BaseType;
            }

            return false;
        }
    }
}
