namespace EncosyTower.Entities.Stats.Analyzers
{
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    internal sealed class StatDataDiagnosticAnalyzer : DiagnosticAnalyzer
    {
        private const string NAMESPACE = "EncosyTower.Entities.Stats";
        private const string STAT_DATA_ATTRIBUTE = $"global::{NAMESPACE}.StatDataAttribute";
        private const string STAT_DATA_DISPLAY = "[StatData]";

        public static readonly DiagnosticDescriptor MustBeStruct = new(
              id: "SG_STAT_DATA_0001"
            , title: "[StatData] can only be applied to a struct"
            , messageFormat: "\"{0}\" is not a struct. [StatData] can only be applied to struct types."
            , category: "StatDataGenerator"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "[StatData] can only be applied to struct types."
        );

        public static readonly DiagnosticDescriptor MustNotBeGeneric = new(
              id: "SG_STAT_DATA_0002"
            , title: "[StatData] cannot be applied to a generic struct"
            , messageFormat: "\"{0}\" is a generic type. [StatData] can only be applied to non-generic structs."
            , category: "StatDataGenerator"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "[StatData] can only be applied to non-generic struct types."
        );

        public static readonly DiagnosticDescriptor StatVariantTypeMustNotBeNone = new(
              id: "SG_STAT_DATA_0003"
            , title: "StatVariantType.None is not a valid argument for [StatData]"
            , messageFormat: "The [StatData] attribute on \"{0}\" uses StatVariantType.None, which is not a valid variant type and will produce no output."
            , category: "StatDataGenerator"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "StatVariantType.None is reserved and cannot be used as the type argument for [StatData]. Use a concrete StatVariantType value instead."
        );

        public static readonly DiagnosticDescriptor TypeofArgMustBeEnum = new(
              id: "SG_STAT_DATA_0004"
            , title: "typeof argument of [StatData] must be an enum type"
            , messageFormat: "\"{0}\" is not an enum. The typeof argument of [StatData] must resolve to an enum type."
            , category: "StatDataGenerator"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "The type passed to [StatData(typeof(...))] must be an enum type."
        );

        public static readonly DiagnosticDescriptor TypeofArgIsGenerated = new(
              id: "SG_STAT_DATA_0005"
            , title: "StatData enum type is generated by another source generator"
            , messageFormat: "\"{0}\" is generated by {3}, so the generator for {1} on \"{2}\" cannot see it. " +
                "Declare \"{0}\" in hand-written source or move it to a referenced assembly."
            , category: "StatDataGenerator"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "StatData enum type is generated by another source generator."
        );

        public static readonly DiagnosticDescriptor StatVariantTypeMustBeDefined = new(
              id: "SG_STAT_DATA_0006"
            , title: "StatVariantType argument of [StatData] must be a declared member"
            , messageFormat: "The [StatData] attribute on \"{0}\" uses the undeclared StatVariantType value {1}, " +
                "which will produce no output."
            , category: "StatDataGenerator"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "The StatVariantType argument of [StatData] must be one of the declared StatVariantType " +
                "members."
        );

        public static readonly DiagnosticDescriptor MustNotBeRecordOrReadOnly = new(
              id: "SG_STAT_DATA_0007"
            , title: "[StatData] cannot be applied to a record struct or readonly struct"
            , messageFormat: "\"{0}\" is a record struct or a readonly struct. [StatData] can only be applied to " +
                "non-readonly structs that are not records."
            , category: "StatDataGenerator"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "[StatData] generates mutable fields and constructors into a partial struct, so it cannot " +
                "be applied to a record struct or a readonly struct."
        );

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
            => ImmutableArray.Create(
                  MustBeStruct
                , MustNotBeGeneric
                , StatVariantTypeMustNotBeNone
                , TypeofArgMustBeEnum
                , TypeofArgIsGenerated
                , StatVariantTypeMustBeDefined
                , MustNotBeRecordOrReadOnly
            );

        public override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
            context.EnableConcurrentExecution();
            context.RegisterSymbolAction(AnalyzeSymbol, SymbolKind.NamedType);
        }

        private static void AnalyzeSymbol(SymbolAnalysisContext context)
        {
            var token = context.CancellationToken;
            token.ThrowIfCancellationRequested();

            if (context.Symbol is not INamedTypeSymbol typeSymbol
                || typeSymbol.HasAttribute(STAT_DATA_ATTRIBUTE, token) == false
            )
            {
                return;
            }

            if (typeSymbol.TypeKind != TypeKind.Struct)
            {
                if (typeSymbol.TryGetSourceLocation(out var location) == false)
                {
                    return;
                }

                context.ReportDiagnostic(Diagnostic.Create(MustBeStruct, location, typeSymbol.Name));

                return;
            }

            if (typeSymbol.IsGenericType)
            {
                if (typeSymbol.TryGetSourceLocation(out var location) == false)
                {
                    return;
                }

                context.ReportDiagnostic(Diagnostic.Create(MustNotBeGeneric, location, typeSymbol.Name));

                return;
            }

            if (StatDataRules.IsSupportedTarget(typeSymbol) == false)
            {
                if (typeSymbol.TryGetSourceLocation(out var location) == false)
                {
                    return;
                }

                context.ReportDiagnostic(Diagnostic.Create(MustNotBeRecordOrReadOnly, location, typeSymbol.Name));

                return;
            }

            var attrib = typeSymbol.GetAttribute(STAT_DATA_ATTRIBUTE, token);

            if (attrib == null || attrib.ConstructorArguments.Length < 1)
            {
                return;
            }

            var arg = attrib.ConstructorArguments[0];

            if (arg.Kind == TypedConstantKind.Enum && arg.Value is byte enumValue && enumValue == 0)
            {
                var location = attrib.ApplicationSyntaxReference?.GetSyntax(token)?.GetLocation()
                    ?? typeSymbol.Locations[0];

                context.ReportDiagnostic(Diagnostic.Create(StatVariantTypeMustNotBeNone, location, typeSymbol.Name));

                return;
            }

            if (arg.Kind == TypedConstantKind.Enum && StatDataRules.IsDefinedVariantType(arg) == false)
            {
                var location = attrib.ApplicationSyntaxReference?.GetSyntax(token)?.GetLocation()
                    ?? typeSymbol.Locations[0];

                context.ReportDiagnostic(Diagnostic.Create(
                      StatVariantTypeMustBeDefined
                    , location
                    , typeSymbol.Name
                    , arg.Value
                ));

                return;
            }

            if (arg.Kind == TypedConstantKind.Type
                && (arg.Value is not INamedTypeSymbol typeArg
                    || typeArg.TypeKind != TypeKind.Enum)
            )
            {
                var displayName = (arg.Value as ISymbol)?.ToDisplayString() ?? arg.Value?.ToString() ?? "?";
                var location = attrib.ApplicationSyntaxReference?.GetSyntax(token)?.GetLocation()
                    ?? typeSymbol.Locations[0];

                context.ReportDiagnostic(Diagnostic.Create(TypeofArgMustBeEnum, location, displayName));

                return;
            }

            if (arg.Kind == TypedConstantKind.Type && arg.Value is INamedTypeSymbol enumType)
            {
                ReportGeneratedEnumType(context, typeSymbol, enumType, attrib);
            }
        }

        private static void ReportGeneratedEnumType(
              SymbolAnalysisContext context
            , INamedTypeSymbol typeSymbol
            , INamedTypeSymbol enumType
            , AttributeData attribute
        )
        {
            var token = context.CancellationToken;

            if (enumType.TryFindEncosyTowerGeneratedType(token, out var generatedType, out var tool) == false)
            {
                return;
            }

            var location = GetTypeOfOperandLocation(attribute, token)
                ?? attribute.ApplicationSyntaxReference?.GetSyntax(token)?.GetLocation()
                ?? typeSymbol.Locations[0];

            context.ReportDiagnostic(Diagnostic.Create(
                  TypeofArgIsGenerated
                , location
                , generatedType.ToGeneratedTypeFullName()
                , STAT_DATA_DISPLAY
                , typeSymbol.Name
                , tool
            ));
        }

        private static Location GetTypeOfOperandLocation(AttributeData attribute, CancellationToken token)
        {
            token.ThrowIfCancellationRequested();

            if (attribute.ApplicationSyntaxReference?.GetSyntax(token) is not AttributeSyntax syntax
                || syntax.ArgumentList == null
            )
            {
                return null;
            }

            var arguments = syntax.ArgumentList.Arguments;
            var count = arguments.Count;

            for (var i = 0; i < count; i++)
            {
                var argument = arguments[i];

                if (argument.NameEquals == null && argument.Expression is TypeOfExpressionSyntax typeOf)
                {
                    return typeOf.Type.GetLocation();
                }
            }

            return null;
        }
    }
}
