#if UNITY_EDITOR

using System;
using EncosyTower.CodeGen;
using EncosyTower.Core;

namespace EncosyTower.Entities.Stats.Generators
{
    [CodeGenerator]
    [ApiForEditor]
    internal sealed class StatSingleExtensionsGenerator : ICodeGenerator
    {
        public GeneratedCode[] Generate()
        {
            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(nameof(StatSingleExtensionsGenerator));
            p.PrintEndLine();
            p.PrintLine(@"#pragma warning disable

using System.Runtime.CompilerServices;
using Unity.Mathematics;
");

            p.PrintLine("namespace EncosyTower.Entities.Stats");
            p.OpenScope();
            {
                var types = GeneratorAPI.Types.AsSpan();
                var typeNames = GeneratorAPI.TypeNames.AsSpan();
                var equalOperators = GeneratorAPI.EqualOperators.AsSpan();
                var sizes = GeneratorAPI.Sizes.AsSpan();

                p.PrintLine("public static partial class StatSingleValueExtensions");
                p.OpenScope();
                {
                    for (var i = 1; i < typeNames.Length; i++)
                    {
                        var type = types[i];
                        var typeName = typeNames[i];
                        var size = sizes[i];

                        p.PrintLine(GeneratorAPI.AGGRESSIVE_INLINING);
                        p.PrintBeginLine("public static StatSingle<").Print(type).Print("> ToStatSingle(this ")
                            .PrintIf(size > 8, "in ", "").Print(type).PrintEndLine(" value)");
                        p.WithIncreasedIndent().PrintLine("=> new(value);");
                        p.PrintEndLine();
                    }
                }
                p.CloseScope();
                p.PrintEndLine();
            }
            p.CloseScope();
            p.PrintEndLine();

            return new GeneratedCode[] {
                CodeGenAPI.GetGeneratedCode(
                      content: p.Result
                    , fileName: "StatSingleExtensions.gen"
                    , pathCombine: GeneratorAPI.COMMON_FOLDER
                ),
            };
        }
    }
}

#endif
