namespace EncosyTower.Core.Analyzers.TypeFlags
{
    internal sealed partial class TypeFlagAnalyzer
    {
        public static readonly DiagnosticDescriptor UnsupportedOwner = new(
              id: "SG_TYPE_FLAG_0001"
            , title: "Type flag owner is unsupported"
            , messageFormat: "Type '{0}' cannot have a type flag because it is {1}."
            , category: "TypeFlag"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "[TypeFlag] supports non-static classes, structs, record classes, and record structs "
                + "that are not ref structs."
            , helpLinkUri: null
            , customTags: Array.Empty<string>()
        );

        public static readonly DiagnosticDescriptor MemberNameConflict = new(
              id: "SG_TYPE_FLAG_0002"
            , title: "Type flag member name is already used"
            , messageFormat: "'{1}' conflicts with the type flag member that [TypeFlag] generates for '{0}'."
            , category: "TypeFlag"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "Rename the member, or remove [TypeFlag] and declare the TypeFlag<T> members by hand. "
                + "[TypeFlag] generates nothing for a type whose generated member names are taken."
            , helpLinkUri: null
            , customTags: Array.Empty<string>()
        );

        public static readonly DiagnosticDescriptor GeneratedBase = new(
              id: "SG_TYPE_FLAG_0003"
            , title: "Type flag owner derives from a generated type"
            , messageFormat: "'{1}' is generated by {2}, so the [TypeFlag] generator for '{0}' cannot see it. "
                + "Declare '{1}' in hand-written source or move it to a referenced assembly."
            , category: "TypeFlag"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "[TypeFlag] plans its generated members from the owner's base types, so every base type "
                + "must be declared where source generators can see it."
            , helpLinkUri: null
            , customTags: Array.Empty<string>()
        );

        public static readonly DiagnosticDescriptor UndefinedOption = new(
              id: "SG_TYPE_FLAG_0004"
            , title: "Type flag option value is undefined"
            , messageFormat: "'{1}' is not a defined {2} value for option '{0}' on '{3}'."
            , category: "TypeFlag"
            , defaultSeverity: DiagnosticSeverity.Error
            , isEnabledByDefault: true
            , description: "WriteAccess takes one TypeFlagAccess member, and Api takes TypeFlagApi members combined "
                + "with '|'. [TypeFlag] generates nothing for a type with an undefined option value."
            , helpLinkUri: null
            , customTags: Array.Empty<string>()
        );

        public static readonly DiagnosticDescriptor IneffectiveApi = new(
              id: "SG_TYPE_FLAG_0005"
            , title: "Type flag option has no effect"
            , messageFormat: "Option 'Api' has no effect on '{0}' because UseExtensions is true."
            , category: "TypeFlag"
            , defaultSeverity: DiagnosticSeverity.Warning
            , isEnabledByDefault: true
            , description: "With UseExtensions, [TypeFlag] generates only fields typed TypeFlag<T> or "
                + "TypeFlag<T>.ReadOnly and the predefined extension methods supply the members. Remove 'Api' or "
                + "set UseExtensions to false."
            , helpLinkUri: null
            , customTags: Array.Empty<string>()
        );

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
            => ImmutableArray.Create(
                  UnsupportedOwner
                , MemberNameConflict
                , GeneratedBase
                , UndefinedOption
                , IneffectiveApi
            );
    }
}
