using EncosyTower.SourceGen.Tests.Diagnostics;

namespace EncosyTower.SourceGen.Tests.Core.EnumExtensions;

internal sealed class DiagnosticContractProvider : IDiagnosticContractProvider
{
    public string FeaturePath => "Core/EnumExtensions";

    public IReadOnlyList<Type> ComponentTypes { get; } = new[] {
        typeof(global::EncosyTower.Core.Analyzers.EnumExtensions.EnumExtensionsAnalyzer),
    };

    public IReadOnlyList<DiagnosticDescriptorContract> Diagnostics { get; } = new[] {
        new DiagnosticDescriptorContract(
              "EncosyTower.Core.Analyzers.EnumExtensions.EnumExtensionsAnalyzer"
            , "SG_ENUM_EXT_FOR_0001"
            , "Type argument of [EnumExtensionsFor] must be an enum type"
            , "\"{0}\" is not an enum type. The typeof argument of [EnumExtensionsFor] must resolve to an enum."
            , "EnumExtensionsForGenerator"
            , DiagnosticSeverity.Error
            , true
            , "The type passed to [EnumExtensionsFor(typeof(...))] must be an enum type."
            , ""
            , Array.Empty<string>()
        ),
        new DiagnosticDescriptorContract(
              "EncosyTower.Core.Analyzers.EnumExtensions.EnumExtensionsAnalyzer"
            , "SG_ENUM_EXT_FOR_0002"
            , "EnumExtensionsFor enum type is generated by another source generator"
            , "\"{0}\" is generated by {3}, so the generator for {1} on \"{2}\" cannot see it. " +
              "Declare \"{0}\" in hand-written source or move it to a referenced assembly."
            , "EnumExtensionsForGenerator"
            , DiagnosticSeverity.Error
            , true
            , "EnumExtensionsFor enum type is generated by another source generator."
            , ""
            , Array.Empty<string>()
        ),
    };

    public IReadOnlyList<SuppressionDescriptorContract> Suppressions => Array.Empty<SuppressionDescriptorContract>();
}
